### ISSUE TITLE
Create similar names with other matching attributes across datasets

### ISSUE THREAD

**Issue by dtromero** [CodeForPhilly/paws-data-pipeline#10]

**Comment by nimandesign** [comment]
At least 1 fake person with the matching name, address, phone number, and email in all 3 data sets: Salesforce, PetPoint, and Vlogistics. Override a couple existing entries so the account ID will still match between the donor in Salesforce and the donation in PDP Salesforce Donations (which doesn't have any user info/PII).

At least 1 fake person with the matching name, address, phone number, and email in the 2 data sets of Salesforce and PetPoint only. 

At least 1 fake person with the same matching, address, phone number, and email in the 2 data sets of Salesforce and Vlogistics. 

At least 1 fake person with the matching name, address, phone number, and email in the 2 data sets of Vlogistics and PetPoint only.

**Comment by jeisey** [comment]
Hi @dtromero @nimandesign  I'm attaching the updated .csv's in a .zip here (haven't really used GitHub so didn't want to overwrite anything). In the .zip are the 4 .csvs from the sample folder with the instances above reflected in the data, and a .doc showing the 4 records I've added with the pertaining fields to reference (and the values they contain) for matching purposes. 
[CfP_PDP_test_match.zip](https://github.com/CodeForPhilly/paws-data-pipeline/files/3919806/CfP_PDP_test_match.zip)
