### ISSUE TITLE
Clean up multiple docker files and READMEs

### ISSUE THREAD

**Issue by tantanchen** [CodeForPhilly/paws-data-pipeline#105]
I'm not sure if we really need 3 dockerfiles and READMEs. It looks like they are just copies too. Can someone confirm and delete the unnecessary ones?

**Comment by urirot** [comment]
Hey @tantanchen ,
actually all are needed. I'll specify by path and explain what each one is for. 
In general it's a good practice to have a dockerfile per docker, and to have different parts of the apps in seperate containers so they are smaller and more manageable. 

- /paws-data-pipeline - that's the project read me. non technical 

- /paws-data-pipeline/src - that's the technical readme for the project and the docker compose file that is using the server dockerfile and the client docker file + is also running the postgres db docker

- /paws-data-pipeline/src/server - dockerfile for the server python + flask app

- /paws-data-pipeline/src/client - dockerfile for our react app + readme about how to run the client locally for dev

let me know if anything is still unclear, or you still think there is a better way to manage this.

**Comment by tantanchen** [comment]
I've added a GettingStarted.md page.
