### ISSUE TITLE
UI - api and master models

### ISSUE THREAD

**Issue by mrcrnkovich** [CodeForPhilly/paws-data-pipeline#106]
In trying to match up the [https://github.com/CodeForPhilly/paws-data-pipeline/blob/master/src/server/models.py](Models) file with the 360 view I'm having a bit of trouble linking the requested information fields in [https://github.com/CodeForPhilly/paws-data-pipeline/issues/80]( 360-Components).  To be more specific:
1. Where are the donation records in Models.py and do they get returned in the /api/360 endpoint?
2. Are the petpoint records for Adoptions or Fostering? How is more than one animal returned with the related salesforce_id? Based on the 360 spec, we're building a table with multiple records for donations and foster/adoption.
3. For volunteer records - where / how are we calculating life hours and YTD hours?

**Comment by urirot** [comment]
@kfettich let's work on placing all the data in the UI on Tuesday
