### ISSUE TITLE
Remove duplicates before matching

### ISSUE THREAD

**Issue by urirot** [CodeForPhilly/paws-data-pipeline#117]
- When matching from a data source, each source should have unique id's for what we are matching.
- This should be generic to all data sources, but currently can be done only on petpoint.
- The column in petpoint that is named `outcome_person_num` should become unique for matching purposes.

**Comment by bbucior** [comment]
@urirot I think this should now be covered from 1f7313342dbe9a1af17f3bd5ad6e2f3bdf456b73. It looks like when we load each PP/SF/etc table, the [matching code will only consider the unique combinations](https://github.com/CodeForPhilly/paws-data-pipeline/blob/344449fc239b6c53d3340caecafbbd6981c5ed2c/src/server/pipeline/match_data.py#L133) of ID + name + email

**Comment by urirot** [comment]
@bbucior got it. closing
