### ISSUE TITLE
Change loader to progress bar for uploading process

### ISSUE THREAD

**Issue by andrew-bishop** [CodeForPhilly/paws-data-pipeline#119]
As I could have noticed we have some problems to indicate when upload is completed without refresh a page. It could be much better if we change simple loader to progress bar with a percentage.

**Comment by urirot** [comment]
@andrew-bishop It's a nice to have feature, but that will require a lot of backend work to keep sending the state of the upload.
More over, this feature is mainly for admins to use to upload the content and it is not something we want to heavily invest time with. eventually this part of the UI should be automated and removed. by automated I mean, that the source CSV's should be extracted from the source providers such as salesforce and then automatically be loaded. 

closing for now
