### ISSUE TITLE
Improve DB setup and configuration

### ISSUE THREAD

**Issue by dkelley** [CodeForPhilly/paws-data-pipeline#120]
This should be config driven and perhaps support migrations. Discuss what sqlalchemy offers with those who know it better.

https://docs.sqlalchemy.org/en/13/core/metadata.html#creating-and-dropping-database-tables

**Comment by c-simpson** [comment]
Using Alembic for user-related tables in https://github.com/c-simpson/paws-data-pipeline/commit/4db091bb5abaac0981e28a154aa5f500346eaa6c

**Comment by dkelley** [comment]
@c-simpson I think this can be closed as well  cc: @urirot
