### ISSUE TITLE
matching issues

### ISSUE THREAD

**Issue by kfettich** [CodeForPhilly/paws-data-pipeline#125]
- [ ] There are people that have numbers (dates) at the end of their name or beginning of their name; this should be removed in preprocessing; e.g. "Jane Doe 4/18" should be "Jane Doe"
- [ ] The matching should compare street addresses across datasets to make a better matching determination; this may only be necessary when the same name appears in multiple tables, but with different email addresses or a NULL email address; e.g. "Jane Doe, janedoe@someemail.com, at 123 streetname Philly" and "Jane Doe, jane_doe@yahoo.com, at 123 streetname Philly" are the same person
- [ ] A shared account should be split, e.g. "Jane and John Doe" should be "Jane Doe" and "John Doe"
- [ ] Names that include nicknames need to be handled, e.g. "Jane (JJ) Doe" should match with "Jane Doe" and "JJ Doe" (essentially 2 first names)
- [ ] Similarly, middle names need to be handled, e.g. "Jane Marie Doe" should match with "Jane Doe" especially when they have the same email address
- [ ] we should also handle duplicated names in the same database, e.g. "Jane Doe" (Salesforce) and "Jane J Doe" (Salesforce) should be highlighted to the user as potentially the same person (esp if email or street addresses match)
- [ ] we should remove periods in email address handles during preprocessing; eg janedoe5@gmail.com and jane.doe.5@gmail.com are the same; especially when they have identical names
- [ ] we should consider common abbreviations of first names in matching, e.g. Jane Doe & Jenny Doe
- [ ] hyphenated last names should be considered for matching, e.g. Jane Doe & Jane Doe-Smith
- [ ] we may want to ignore certain email addresses that are expected to have different names associated with them (e.g. accounting@somebusiness.com)
- [ ] consider degress at the end of the name when matching (e.g. Jane Doe and Jane Doe VMD)
- [ ] first name and last name mixed up (eg Jane Doe and Doe Jane)

**Comment by bbucior** [comment]
For nicknames, we might be able to use this [list](https://github.com/carltonnorthern/nickname-and-diminutive-names-lookup/blob/master/names.csv) or [Python module](https://github.com/constituentvoice/PyNameMatcher/blob/master/pynamematcher/matcher.py)
