### ISSUE TITLE
Investigate De-Dupe Efforts PAWS Has Completed

### ISSUE THREAD

**Issue by eudoralinde** [CodeForPhilly/paws-data-pipeline#130]
Data cleanup needed by PAWS; Data needs to be de-duped and cleaned up in Sales Force (high value for PAWS).

**Definition of Done:** Chris to reach out to Lauren to discuss de-dupe efforts at PAWS, set meeting if needed to walk the team through what has been done thus far for de-duping.

**Comment by kfettich** [comment]
PAWS has given us a dataset of manual matches that they have already done - this can be used for validation of our matching, and manual correction of matches before we present the PDP to PAWS; Volgistics & Salesforce have been matched more comprehensively than Salesforce & ShelterLuv
