### ISSUE TITLE
Setup github CI/CD to build containers

### ISSUE THREAD

**Issue by dkelley** [CodeForPhilly/paws-data-pipeline#146]
After talking to Linode, it sounds like it would be helpful for PAWS to use github to build images.

**Comment by c-simpson** [comment]
Is there a plan for testing? If so, this seems like to place to integrate it.

**Comment by dkelley** [comment]
This is an example build file
https://github.com/CodeForPhilly/prevention-point/blob/master/.github/workflows/release-containers.yml

**Comment by dkelley** [comment]
@c-simpson @urirot testing was added as a separate issue, can we close this?
