### ISSUE TITLE
/api/statistics should not return 404 if last_execution.json not present

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#147]
If the `last_execution.json` file has not yet been written (as at initial deploy), `admin.apy/listStatistics()` will return a 404 status. This seems incorrect as the issue is not a bad request from the client.  A 204 (No Content) might be better but it's probably best to send a 200 with a Null JSON payload.

**Comment by dkelley** [comment]
Good call, I think @urirot may have added the json file but was likely same issue if data wasn't run. So I'll fix it.  Good catch!

**Comment by c-simpson** [comment]
I added a fix in PR #148 , which is pending.

**Comment by c-simpson** [comment]
Fixed with PR #148
