### ISSUE TITLE
Determine how to manage cluster access

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#154]
We need to 
- figure out how to access the Linode cluster that's available to us
- determine who should be able to push what to it

**Comment by dkelley** [comment]
Server info 
```
Welcome to Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-72-generic x86_64)

 * Introducing self-healing high availability clusters in MicroK8s.
   Simple, hardened, Kubernetes for production, from RaspberryPi to DC.

     https://microk8s.io/high-availability

 * Canonical Livepatch is available for installation.
   - Reduce system reboots and improve kernel security. Activate at:
     https://ubuntu.com/livepatch
```

**Comment by dkelley** [comment]
Per conversation with @c-simpson let's plan to migrate our deployment to k8s following linode guide here 
https://www.linode.com/docs/guides/getting-started-with-kubernetes/

**Comment by c-simpson** [comment]
Access is through CFP administration group  via our pushes and notifications to them, so very limited.
