### ISSUE TITLE
Decide on real front-end web server

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#155]
The flask server is fine for development, but we'll need a real one when we go live. 

- Nginx? 
- Gunicorn
- Others?

**Comment by dkelley** [comment]
I'd vote https://flask.palletsprojects.com/en/1.1.x/deploying/uwsgi/

**Comment by c-simpson** [comment]
Nginx seems like a fine solution. Let's go with that.
