### ISSUE TITLE
Add PAWs manual matches in addition to those generated by the pipeline

### ISSUE THREAD

**Issue by sposerina** [CodeForPhilly/paws-data-pipeline#157]
PAWs could possibly upload a csv to specify matches that won't be discovered by the current matching methodology.

- [x] Determine how to get ShelterLuv ID from available data
- [x] Give reasons for missed matches from `match_deltas.csv`
- [x] Manually adjust matches so `pdp_contacts` table reflects the manual matches provided by PAWS
- [ ] Create unit tests to monitor the health of the pipeline matches

**Comment by AkshatVas** [comment]
Adding myself to this issue. I'm interesting in helping design the solution to this problem.

**Comment by sposerina** [comment]
In the PAWs dropbox I created a new directory called manualMatches. PAWs provided a spreadsheet with manual matches that I filtered into just id columns and saved as manualMatches.csv. 

First I was going to import these matches into a separate table and then compare against the results of the pipeline to see if anything from the manual matches can be automated in the pipeline. Next I wanted to implement functionality that allows PAWs to upload there own custom matches but still in a separate table to not pollute the automated matching. Finally the manual and pipeline matches both need to be visible in the 360.

**Comment by urirot** [comment]
@sposerina should we create a UI issue and start working on a mock for that form?

**Comment by sposerina** [comment]
That's a good idea. I already created a mockup that allows users to adjust the matches. I'll create a new issue and put the mock up on dropbox as it contains real data.

**Comment by sposerina** [comment]
@AkshatVas Were you able to to determine if that spreadsheet provided any additional matches?

**Comment by AkshatVas** [comment]
Hey, @sposerina! Working on it as we speak. It seems my first attempt to ingest the raw data was not successful, so I'm trying again.

**Comment by AkshatVas** [comment]
Edited the issue description to reflect our discussion today

**Comment by sposerina** [comment]
The ShelterLuv IDs specified in the ```shelterluv_people.xlsx``` use the ```ID``` field instead of ```Internal-ID``` that we use as the ```source_id``` in the ```pdp_contacts``` table. We can either change the ```source_id``` stored in the ```pdp_contacts``` to use the ```ID``` field  or create a separate mapping table. One argument for changing the id is I believe the shorter id is used as part of the URL for viewing user data in the ShelterLuv app. Having this ID around means we can easily generate URLs in our client for navigating directly to a user's page within the ShelterLuv app.

**Comment by AkshatVas** [comment]
Did we make a decision on how we want to approach this? I was thinking about it, and I don't have a strong preference. It's probably best for us to represent the `pdp_contacts.shelterluv_id` in a way that makes the most sense to our users. Given the `manual_matches `table, would that be `ID` field?

**Comment by sposerina** [comment]
I created a file called `match_deltas.csv` that contains the difference between the pipeline and manual matches provided by PAWS. I added an additional column called `pdp_records` as  a way to add some additional context. It states how many records were matched (have the same matching_id) for the `contact_id` provided. For example, if the `pdp_records` column has a value of one and two ids are specified in the manual match there is most likely a problem. On the other hand, if the `pdp_records` has a value of 3 or greater this is mostly likely due to the pipeline doing a better job and matching more records. Next steps is go through each row (390 total) and come up for reasons why the matching logic didn't catch the match e.g. (a record uses a nickname instead of the first name).

**Comment by AkshatVas** [comment]
Did we get a chance to review some the `match_deltas` record? Any early insights?
If not, I'll try to go through a few and see what I learn

**Comment by sposerina** [comment]
I summarized the miss matches in the file `match_deltas.xlsx`. I went through each mismatch and tried to categorize it and than created a pivot table on another sheet to total each category. Some of these mismatches can be fixed with tweaks to the pipeline but others will still need to be manually adjusted. Another idea that came up while reviewing the mismatches was to use these categories to create unit tests to the monitor the overall health of the pipeline.

**Comment by AkshatVas** [comment]
Update from my last conversation with Stephen:

Our current thinking is to put manual matches in a separate table and handle same record updates by appending the changes.

I took a look at our `flow_script.py`. It looks like we're running the matching function on rows classified as updated. Is that right? And, are we doing that because we think there may be new rows that are duplicate entries? For example, could we see two Salesforce records for the same contact?

If so, we'll need to account for that possibility somehow.

**Comment by AkshatVas** [comment]
@sposerina It might be a good idea for us to walk through the matching flow together, come up with a proposal, and share with the larger team before settling on the direction.

**Comment by sposerina** [comment]
Yeah let's do that. I started coding the ability to upload the manual matches CSV through the administrative interface. During the execution of the pipeline the manual matches will be loaded into a separate data frame and will skip the cleaning/normalization stage since it's just ids. Another code change will have to occur in `manual_matches.py` at around line 65. I haven't coded this yet and feel free to play around in the branch `manual_matches`. The idea being that in addition to matching on the defined criteria it will also use the manual matches data frame when assigning ids.

**Comment by sposerina** [comment]
Closing this as remaining tasks are migrated to issues #281 and #231
