### ISSUE TITLE
Restructure web interface for admin functions

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#160]
The current web interface has a single page (/upload) for handling raw data. We also need to support user management, so it seems to make sense to create an admin area. It would be desirable to have this under one or more admin function-only components to simplify access control. 

The user admin stuff will probably need several pages. We could add drop-downs to the current ADMIN toolbar/header link or add a secondary admin header directly below the current one.

**Comment by c-simpson** [comment]
@uri , @dcstlouis  I'm making progress on #290  and will need UI for    

- Creating users
- Updating users (names, roles, active, password)

These should be under Admin but I'll leave it to you folks to figure out the best way to handle navigation / menus, etc.  I'm working on more specific requirements but wanted to give you some notice.

**Comment by urirot** [comment]
@c-simpson - Maybe this should this just be added in the admin page, as a tab?

**Comment by carrollsa** [comment]
I added a `Users` tab that displays all users and allows for activation/deactivation and user creation via buttons that display dialog/modal popups.
