### ISSUE TITLE
UI - 360 page

### ISSUE THREAD

**Issue by urirot** [CodeForPhilly/paws-data-pipeline#166]
Show details of a person after selected from the table.    
The data we want to show is: contact info, donations, adoptions and shifts. reference the existing code and the attached [image](https://codeforphilly.slack.com/files/UNXAWF9CL/F01B775FGE7/screen_shot_2020-09-22_at_8.29.48_pm.png).
- Make the rows in the search results table clickable
- After clicking on a contact the user will see the 360 view instead of the table and the search bar
- Use the existing layout and components to show the details for this contact
- Add a back button so the user can navigate back to the search view
- Contact_details will now be an array, for now we can just take the details from the first random item that has good data.

**Comment by urirot** [comment]
@dcstlouis When I said a new page for the contacts 360 view, I just meant a new component/class, no need to redirect the url. just making sure I didn't confuse you with that.

**Comment by urirot** [comment]
@dcstlouis update :) 
if you pull the latest from master you can now use the 360 API to get the contact_details. usage example:    
`localhost:3333/api/360/18`    
this uses the matching_id as we discussed.     
Notice the response has greatly changed, so we will need to make some adjustments on the UI side as well.

the rest of will also be added to the response, slowly but surely. this data (shifts, donations) shouldn't change from what we have in the current response. adoptions will probably change since we are fetching it from shelterluv where we used to get it from petpoint.

**Comment by dcstlouis** [comment]
Pushed code to issue-166-360Page branch to:
- Link search results to 360 view
- Include back button on 360 view
- Remove search bar from 360 view

Still need to:
- Make entire table row clickable (right now it's just the matching id)
- Show donations, adoptions and shifts (right now it's just contact info)

**Comment by urirot** [comment]
The latest version in master now returns the 360 for a person with his shifts and donations, will try to add adoptions as well, but you can start playing with the new response. @dcstlouis

**Comment by urirot** [comment]
adoption data is also in the response! @dcstlouis check slack for an additional file you will need to add to the project for the shelterluv api to work

**Comment by dcstlouis** [comment]
Pushed code to include donations, adoptions, and volunteer history on the DataView page.

Still need to:
- [ ] Incorporate details about volunteer activity (including start date, life hours, year-to-date hours)
- [ ] Add component to display adoption details

**Comment by urirot** [comment]
@dcstlouis json is back! 
so all there is to do now is populate those volunteer stuff and then we can close this.
 thanks @bbucior
