### ISSUE TITLE
500 because salesforcedonations table does not exist

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#181]
After PR #172 (user_mgmt) was merged into master [(1eb9735)](https://github.com/CodeForPhilly/paws-data-pipeline/commit/1eb973537ee4a67861232c610ba6157935f15ae8)    (but probably unrelated) :  

After `docker-compose down -v` and `up`

- From UI Admin page, load the three non-ZZZ files in Dropbox/latest raw data/ShortExcerpt 
- Execute
- In 360, search for 'amo' 
- Click second line (source:volgistics)

results in 
`ERROR:  relation "salesforcedonations" does not exist at character 15`    
caused by    
`STATEMENT:  select * from salesforcedonations where contact_id like ...`   

It looks like we could add a check for that table's existence or would it make sense to create all the necessary tables via Alembic up front?

**Comment by urirot** [comment]
@c-simpson think we can close this? 
Probably nothing to worry about, we shouldn't query before pipeline has finished successfully.

**Comment by c-simpson** [comment]
I'll close this once we finish the new SFD import.
