### ISSUE TITLE
Volgistics data from 360 API returns same street address for multiple people

### ISSUE THREAD

**Issue by dcstlouis** [CodeForPhilly/paws-data-pipeline#183]
Sending a GET request to api/360/{matching_id} sometimes returns incorrect data attributed to the Volgistics dataset where the "street_and_number" value is the same across multiple different people

**Comment by c-simpson** [comment]
It looks like **all** the Volgistics records are showing this. 

```
select * from pdp_contacts
where source_type = 'volgistics'
order by _id
```
I get 941 records, each with  
 'street_and_number' = 'Sigel'   
 and 'apartment' = '1837.

**Comment by c-simpson** [comment]
The street and apartment for all the volgistics records come from the last person in the  `Volgistics_All volunteer information (stock).xlsx` file .

See Slack #pdp_private for details.

**Comment by urirot** [comment]
@c-simpson Thanks, It's fixed, you can see in this [commit](https://github.com/CodeForPhilly/paws-data-pipeline/commit/96d22e7fa1b742f2d3a30713b2a353879e1360fd).

closing for now, even though the address still needs some work to it. we can open a separate issue when needed
