### ISSUE TITLE
500: "The string supplied did not seem to be a phone number."

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#184]
When running the code merged in #176 , 
Got `phonenumbers.phonenumberutil.NumberParseException` when executing these uploaded files:

> shelterluvpeople.xlsx
> Volgistics_All volunteer information (stock).xlsx
> Salesforce_PAWS Donation (all Time) (excel).xlsx

```
paws-compose-server |   File "/app/datasource_manager.py", line 87, in normalize_phone_number
paws-compose-server |     parsed_number = phonenumbers.parse(number, "US")
paws-compose-server |   File "/usr/local/lib/python3.7/site-packages/phonenumbers/phonenumberutil.py", line 2845, in parse
paws-compose-server |     "The string supplied did not seem to be a phone number.")
paws-compose-server | phonenumbers.phonenumberutil.NumberParseException: (1) The string supplied did not seem to be 
a phone number.
```

**Comment by c-simpson** [comment]
Current files says:
     shelterluvpeople-2021-02-10--01-21-32.csv
    volgistics-2021-02-10--01-20-47.csv
    salesforcedonations-2021-02-10--01-22-16.csv
    volgisticsshifts-2021-02-10--01-20-48.csv


which is hard to match up with files

**Comment by c-simpson** [comment]
Easier - uploading and executing these two files will cause the exception:
 
`Volgistics_All volunteer information (stock).xlsx`
`shelterluv_people.xlsx`

**Comment by c-simpson** [comment]
`Volgistics_All volunteer information (stock).xlsx` has some phone numbers with four digits, some with five, some with six, one with eight.

`shelterluv_people.xlsx` has lots with just the value '1'.

**Comment by mtdamert** [comment]
Cris, thanks for tracking this down!

It looks like the phone number library crashes when it gets a phone number that's 1 digit, so I created a pull request.

Unfortunately, I was unable to test - when I try to upload any file, I get an error message:
```
paws-compose-server | sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "pdp_user_roles" does not exist
paws-compose-server | LINE 1: select role from pdp_user_roles
paws-compose-server |                          ^
```

I manually looked through the Volgistics file, but didn't see anything there that should crash the library.

**Comment by c-simpson** [comment]
Mike, you are running into #180 .   It should be fine after a restart of the server container, and I've got a ~~fix~~ hack I'll post in a bit.

**Comment by tiaagustinah** [comment]
Error While Parsing Phone Number: (1) The string supplied did not seem to be a phone number.
