### ISSUE TITLE
Standardize all dates in our DB

### ISSUE THREAD

**Issue by urirot** [CodeForPhilly/paws-data-pipeline#195]
Currently, our date formats are mixed in the DB which causes some patches on the Frontend side.
For Example:
Dates in `pdp_contacts` are in the format of: `Jan 27, 2021, 9:57:37 AM`
While `volgistics_shifts` are like this: `07-11-2019 `

We want to make them all as we have them in the `pdp_contacts` which is the timestamp format of Postgres.

**Comment by c-simpson** [comment]
We appear to have achieved this - all dates now YYYY-MM-DD, some with times.
