### ISSUE TITLE
DNS issues for deployment

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#197]
We need to get the desired DNS name for the MVP deployment, presumably SOMETHING.phillypaws.org.  PDP? Or as the P would be assumed, DP?   Who would decide this?

We'll also need the technical contact (in #pdp_private) who can edit the DNS record to add the CNAME record at the appropriate time.

**Comment by c-simpson** [comment]
For now, 
DNS Information-Use Non phillypawsrelated for short term - whatever URL comes out of Linode

**Comment by dkelley** [comment]
@c-simpson can we close this for now?

**Comment by c-simpson** [comment]
Yes
