### ISSUE TITLE
improve volgistics data gathering

### ISSUE THREAD

**Issue by urirot** [CodeForPhilly/paws-data-pipeline#203]
Volgistics data is gathered from CSV with many different tabs. 
We are currently gathering the information from Master and Assignments tabs. 
in the 360 we are showing last 3 shifts based on the assignments tab, which has a from date and does not reflect the actual volunteering, but the assignment for a task. 

- A specific task here is to get the tasks date to be accurate to actual shifts and not just assigned shifts
- A robust solution here would be to understand the different tabs, and create a complete table in our DB with all the interesting information from the various tabs. 

note: master tab is used for matching, some of it is not but it is already populated in the pdp_contacts DB in the json section, so no need to relook at this tab.

**Comment by c-simpson** [comment]
@urirot   Think we've achieved this?

**Comment by urirot** [comment]
@c-simpson I don't know really, but I think we can close this and recreate one if needed in the future. don't think there's a request for this now
