### ISSUE TITLE
nginx exposes the need for app restructuring

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#225]
**Abstract**: _We need to separate handling web requests from the long-running processes._

In testing Dan's   [nginx_setup](https://github.com/CodeForPhilly/paws-data-pipeline/tree/nginx_setup)     branch, I'm seeing timeouts from **nginx** when running `/api/execute` on the full data set.  **nginx** has a timeout setting of 60 seconds for the response from the server, then sends a 504:

```<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.19.6</center>
</body>
</html>
```

`handleExecute()` is expecting JSON back and doesn't check the response status before trying to parse the html, resulting in an uncaught error. 

The bigger issue is that the execute takes so long to run (right at an hour on my machine for 95937 rows). There's probably room for improvements in matching speed but it's likely to always be minutes at best, and it's bad practice to leave web requests hanging out that long. Dialing up the nginx timeout could only be a temporary hack as we need to provide some feedback to the user on what's going on. (We can watch the logs when running locally but the user will have no way to know if things are still running or not.) 

Here's one idea based on something I've done before:
- Move the execute (and probably intake as well) process into its own container, 'processing'
- Set up a work queue using redis and [RQ](https://python-rq.org/) 
- Pass intake/execute jobs from the API server to the processing container. To avoid shared storage, the API server can drop the uploaded files as blobs into the DB. 
- The process in the processing container can pull jobs from the work queue, grab the files from the DB, and start working. 

- The processing container can have a message queue going back to the API server, and the React client can poll for status, at which point the API server sends back the latest status ('**34% done**') to display to the user. 

I'm happy to sketch out in more detail.

**Comment by urirot** [comment]
@c-simpson - one possible approach
https://philchen.com/2019/07/15/scaling-a-python-flask-app-with-nginx-using-multiple-containers-with-docker-compose

**Comment by urirot** [comment]
@c-simpson is this still relevant?

**Comment by c-simpson** [comment]
More details for this in #336.
