### ISSUE TITLE
pipeline conflicts - contacts matching multiple groups 

### ISSUE THREAD

**Issue by urirot** [CodeForPhilly/paws-data-pipeline#231]
when running the pipeline there are some instances of warnings we are printing to identify contacts that are matching multiple groups. we should investigate this, and decide what to do. 

example:
```
paws-compose-server | [2021-03-18 22:13:52,184] WARNING in match_data: Source salesforcecontacts with ID 0033900002A1SVqAAN is matching multiple groups in pdp_contacts (14421    14367
paws-compose-server | 23051    22956
```

**Comment by c-simpson** [comment]
When running with #310  I'm seeing about 20 of these warnings.

**Comment by sposerina** [comment]
Investigating one of these records, the warning indicates the presence of a "glue" record. A row is being processed by the pipeline and matches records that have different matching ids. This can occur if the two existing records don't share a secondary criteria to complete the match BUT the glue record matches one but not both of the other records secondary criteria.

| Matching ID | First Name  | Last Name |Email|Mobile
| ------------- | ------------- | ------------- |-------------|-------------|
|1 | John  | Doe  | jd@aol.com|555-5555|
| 2 | John  | Doe  |doeDude@gmail.com|555-5556|
| glue record |  John | Doe | jd@aol.com |555-5556|

At first glance it seems appropriate just to roll all of these records into the same id. I'll continue to look at the other records to see if they follow the same pattern.

**Comment by urirot** [comment]
@sposerina any progress with this?
