### ISSUE TITLE
Delete helpers.py ?

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#233]
`/src/server/helpers.py` was added in PR #123 but  does not appear to be imported or referenced by anything and breakpoints set within don't get hit by any activity I'm able to generate. 

Is this dead code that should be removed?

**Comment by bbucior** [comment]
Looks like some dead code merged from another WIP branch at the time, so I think it can be safely removed.

**Comment by urirot** [comment]
done @c-simpson 
https://github.com/CodeForPhilly/paws-data-pipeline/commit/f0b0f337c5f11c93d9d6d8c1fe96d47ec446159e
