### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#236]
1 - We should determine who owns the code we're writing.

2 - With the answer to # 1,  we/they should determine what license the code will be published under _e.g_.,  [MIT](https://opensource.org/licenses/MIT) which is largely "do what you want, but don't blame us".

Here's some detailed info from GitHub:  [licensing](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository)

3 - We need to ensure that we are complying with the license conditions of the code we're using, which includes:

Python
Flask  &nbsp; &nbsp; &nbsp;  ( [License](https://flask.palletsprojects.com/en/1.1.x/license/#source-license) )
pandas
numpy
fuzzywuzzy
sqlalchemy
sqlalchemy_utils
psycopg2-binary
python-Levenshtein-wheels
xlrd
openpyxl
requests   &nbsp; &nbsp; &nbsp; ( [License](https://github.com/psf/requests/blob/master/LICENSE) )
pytest
flask-jwt-extended
alembic
flask-cors

**Comment by kfettich** [comment]
...assuming we go with an MIT license....

Python ([license](https://docs.python.org/3/license.html#psf-license-agreement-for-python-release)) - compliant
Flask ([license](https://flask.palletsprojects.com/en/1.1.x/license/#source-license)) - compliant
pandas ([license](https://pandas.pydata.org/pandas-docs/stable/getting_started/overview.html#license)) - compliant
numpy ([license](https://numpy.org/doc/stable/license.html)) - compliant

more to come

**Comment by c-simpson** [comment]
This seems to give dependencies for the client too:
https://github.com/CodeForPhilly/paws-data-pipeline/network/dependencies

**Comment by kfettich** [comment]
Going through the dependecy list here: https://github.com/CodeForPhilly/paws-data-pipeline/network/dependencies

Dependencies defined in `src/package-lock.json` (all compliant): 

- `salesforce/buffer-equal-constant-time`: BSD-3-Clause License; compliant
- `Brightspace/node-ecdsa-sig-formatter`: Apache-2.0 License; compliant
- `auth0/node-jsonwebtoken jsonwebtoken`: MIT License; compliant
- `auth0/node-jwa`: MIT License; compliant
- `auth0/node-jws`: MIT License; compliant
- `lodash/lodash`: MIT License; compliant
- `vercel/ms`: MIT License; compliant
- `feross/safe-buffer`: MIT License; compliant
- `npm/node-semver`: ISC License; compliant
