### ISSUE TITLE
Clear 'Upload Files' list after successful upload 

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#237]
After a successful upload, the chosen files still appear as ready to upload ("X files selected"). That should be cleared so user does hit hit upload button again.   

Also, after a successful upload the uploaded files are present in both `/static/raw_data` and  `/static/raw_data/current` - do we need both?

![image](https://user-images.githubusercontent.com/11001850/112163997-eb730780-8bc3-11eb-852d-82fd8d3ece0e.png)

**Comment by urirot** [comment]
- fixed browse files button not being initialized.
- didn't fix the later: we do need both. we are using only the `/current`  but the rest is still stored for backup

closed with this [commit](https://github.com/CodeForPhilly/paws-data-pipeline/commit/f27f8c95ac66348015349a11d3be88e3a31f8fcd)
