### ISSUE TITLE
clean UI warnings

### ISSUE THREAD

**Issue by urirot** [CodeForPhilly/paws-data-pipeline#246]
When running npm start there are still some warnings in App.js and Check.js. 
Should be cleaned, so the npm start will be clean of warnings.

**Comment by c-simpson** [comment]
App.js:
 
-   Line 4:11:   'userName' is assigned a value but never used     
-   Line 126:11:  'access_token' is assigned a value but never used 
-   Line 131:11:  'access_token' is assigned a value but never used  
-   Line 131:25:  'setToken' is assigned a value but never used      
- 

Check.js:
- Line 80:8:  React Hook React.useEffect has a missing dependency: 'authCheck'. Either include it or remove the dependency array
