### ISSUE TITLE
CI/CD needs a .dockerignore for server

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#269]
We need a [.dockerignore](https://docs.docker.com/engine/reference/builder/#dockerignore-file) file for the server branch to ensure we don't bundle up any junk in the images.

We should also review the existing one in /client to see if there's more stuff we should exclude.

**Comment by dkelley** [comment]
I didn't see a .dockerignore in your branch, but I added one in #323 . Let me know if you see a conflict, but we can close this after the merges anyway.  I also think the deployment on linode tested this branch? @c-simpson
