### ISSUE TITLE
Verify uWSGI security

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#270]
When the server runs, uWSGI emits this several times:   
  
`*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***`

Do we need to create a user for it / set a different uid?

**Comment by dkelley** [comment]
May be fixed with branch uwsgi_user which adds pawsapp user

**Comment by dkelley** [comment]
@urirot @c-simpson can we look to merge the uwsgi_user branch? so we can close this?

**Comment by c-simpson** [comment]
@dkelley   I can't remember if I tested this - did you do a PR for it?
