### ISSUE TITLE
Ensure API server can get secrets as needed

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#271]
We currently store the secrets in `secrets.py` but we can't include that file in images processed through GitHub actions as those are accessible to anyone. 

The code needs to be able to get secrets no matter where the code is executing:

- Locally via `secrets.py`   (and handle exceptions if not)
- Under k8s via [secrets file](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod)
- Under k8s via [environment variables](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables)

**Comment by dkelley** [comment]
I assume this file will change per env (or could), so like you said it should be included as an actual docker "secret" or what works for k8s.
