### ISSUE TITLE
RFM (Recency, Frequency, Monetary) Single Score from Lauren

### ISSUE THREAD

**Issue by jwtruver** [CodeForPhilly/paws-data-pipeline#285]
From Conversation with Lauren on 210223:
The last time they engaged...and then the history of their engagement
This would be great for qualification resources
https://www.google.com/search?q=rfm+score&rlz=1C5CHFA_enUS719US720&oq=rfm+score&aqs=chrome..69i57j0l9.1727j0j7&sourceid=chrome&ie=UTF-8
An RFM analysis tells you which customers are likely to respond to a new offer. The RFM analysis assigns a 3 digit RFM score (from 111 thru 555) to each customer. A 555 indicates that a customer has purchased a product or service most recently, most frequently, and at the highest monetary value.

**Comment by kfettich** [comment]
https://thegood.com/insights/rfm-analysis-convert/

**Comment by jwtruver** [comment]
from Cris: https://codeforphilly.slack.com/archives/CMLQV4JLA/p1614128594006500Here's a quick intro: https://clevertap.com/blog/rfm-analysis/
CleverTapCleverTap
RFM Analysis for Customer Segmentation | CleverTap
RFM analysis segments customers on recency, frequency, and monetary value can indicate customer engagement, retention, and customer lifetime value.

**Comment by kfettich** [comment]
I'd propose that we calculate this score for 3 areas: 
1) donations
2) fostering (recency and frequency are self-explanatory; monetary value we may want to replace with total number of animals)
3) volunteering (recency and frequency same as above; monetary value could be replaced with total number of hours)

**Comment by jwtruver** [comment]
going to focus on donations first

**Comment by jwtruver** [comment]
Ben added the code that calculates the bins to github.
