### ISSUE TITLE
Track user logins or 'last user login'

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#295]
Karla mentioned the value of an admin being to see when a user last logged in. It would be easy to add a column to the pdp_users table and update each time the user logs in. 

Is this enough?  Is there more data we need to collect/show?

My inclination would be to just capture log-ins, not refreshes.

**Comment by kfettich** [comment]
as discussed, we'll create separate userIDs for each user (manually if need be for MVP), and track each login per userID, each failed login, and number of 'refresh'-es

**Comment by c-simpson** [comment]
I'll close this when all the pieces are in place. 

TODO: Log refreshes, build query, sketch UI for display
