### ISSUE TITLE
Define password rules

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#302]
We need to come up with some basic rules for passwords (obligatory [xkcd 936](https://xkcd.com/936) ).
I think the main threat is not brute-force but weak passwords (and adding 2FA  #230) will fix that.

How about:

- Length > 11 chars
- Does not contain username
- lower() does not contain 'password', 'paws', 'philly', 'dog', cat'

I started playing with this in [password_is_strong()](https://github.com/CodeForPhilly/paws-data-pipeline/blob/e20f5dd7d28047cb23fda8aef303ebcddbbfa04c/src/server/api/user_api.py#L36)

**Comment by c-simpson** [comment]
@kfettich Any thoughts?

**Comment by fliphil** [comment]
Would like to tackle this, @c-simpson unless you already have it complete or do not want to give it up.

**Comment by c-simpson** [comment]
Great!  We decided to just require length but the 'likely word' check still needs to be done. Thanks.


https://github.com/CodeForPhilly/paws-data-pipeline/blob/6427a812041f606495e1d34120bc3d1db5015b01/src/server/api/user_api.py#L36-L60

**Comment by carrollsa** [comment]
I just wrote these rules into the `yup` validation schema. They will be included when I finish the user management page.
