### ISSUE TITLE
Determine target screen resolution for UI

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#304]
We should have an idea of the kind of monitors/resolutions PAWS uses to make sure we're testing with representative settings. 

In Windows:    
Right-click in Desktop, click 'Display Settings' near bottom of pop-up. When 'Display' menu appears, scroll down to 'Scale and Layout' and get 'Display Resolution' value.

**Comment by kfettich** [comment]
Thanks Cris! I'll make sure to check with PAWS!

**Comment by dkelley** [comment]
Don't modern UI layout handle this?

**Comment by urirot** [comment]
Closing this - we should be able to have a good view in any screen size (laptop and up).
Let's open specific issues if there are some bad screens
