### ISSUE TITLE
Create a web interface for user-friendly manual upload of csv data

### ISSUE THREAD

**Issue by sposerina** [CodeForPhilly/paws-data-pipeline#31]
A simple web interface will be created to allow non-technical users to upload the latest data csv files into the database; the following should be considered: 

- users uploading files should be identified in some way (ie, not anyone from anywhere in the world should be allowed to upload files) 
- the files uploaded should not be anything other than csvs, and should follow a predefined naming convention
- files should not exceed a predefined size

**Comment by urirot** [comment]
this can be closed right @sposerina ?

**Comment by sposerina** [comment]
I think so. For point 1, the application is secured through zero tier so no application level authentication is needed. There isn't a naming convention other than appending a timestamp to the CSV but that issue is addressable in #39. Validation logic is implemented on the server side.
