### ISSUE TITLE
Need obvious sort order for 360 Search results

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#312]
When searching (_e.g._, for 'Jones'), the results seem to be ordered by 'count(matches) desc'. This doesn't seem the most obvious choice because to find a particular Jones, you'd have to look in the 3-match group, the 2-match group, then the single group. 

There appears to be no order at all within an n-match group, so you have to scan the entire group.

I'd suggest sorting by last name, first name, then maybe match count.

**Comment by kfettich** [comment]
Good catch; I propose we sort people alphabetically; once we include the RFV score, we can order people by that, which may be more valuable; but alphabetically would give users a logical way of finding people

**Comment by c-simpson** [comment]
@kfettich   Alphabetically by (last name, first name)?

**Comment by c-simpson** [comment]
@dcstlouis   I added an `order by`clause to the SQL queries in common_api.py :


https://github.com/CodeForPhilly/paws-data-pipeline/blob/d5de11042be91035ebde1c8cee8de10935a9a28a/src/server/api/common_api.py#L52

and https://github.com/CodeForPhilly/paws-data-pipeline/blob/d5de11042be91035ebde1c8cee8de10935a9a28a/src/server/api/common_api.py#L57
   

These return the records sorted by  lastname,firstname but it appears that the real sorting happens in Search.js:

https://github.com/CodeForPhilly/paws-data-pipeline/blob/d5de11042be91035ebde1c8cee8de10935a9a28a/src/client/src/pages/DataView360/Search/Search.js#L111-L113


I'm not clear what's happening there but it seems to sort by `matching_id desc`.  Can you take a look at it  and see if you can see a way to make it sort match groups by name and not id or group length? 
  
This branch has the `order by` clauses
https://github.com/CodeForPhilly/paws-data-pipeline/tree/312-sort-order
or you can just copy from above.   But if you are sorting in JS, maybe it doesn't matter what you get from the search API.
