### ISSUE TITLE
About us page not up to date

### ISSUE THREAD

**Issue by kfettich** [CodeForPhilly/paws-data-pipeline#320]
The "about us" page should be displaying the text from [this google doc](https://docs.google.com/document/d/1JxHqEb6bqJq_CckSbREyTNITWUS-txIdXP1qBModnzo/edit?usp=sharing) rather than the project description from GitHub

**Comment by c-simpson** [comment]
What's on the sandbox is several weeks old. I'll merge in Donna's changes soon.
