### ISSUE TITLE
Add Log Out Button

### ISSUE THREAD

**Issue by jwtruver** [CodeForPhilly/paws-data-pipeline#322]
Let's add a "Log Out" Button.

I've added this to both MVP and also v1.0.

If this would cause any sort of security issue, we need for MVP. If not, this can wait until 1.0.

**Comment by c-simpson** [comment]
Where should it be placed?

**Comment by dkelley** [comment]
We should probably also show "who" is logged in and that could a drop-down with the logout button?  Too complicated? Add logout to nav bar for now?

**Comment by kfettich** [comment]
As a simple solution, a log-out button in the nav bar, top right corner,
will work. I like Dan's suggestion, especially if multiple users will be
logging in -> probably would be useful to show who is logged in, what
permissions level (user, editor, admin) and a log out button. But this more
involved solution can put in v1.0, I think. If it's a security issue, I'd
say go with simple solution, if it isn't, then we can work on Dan's
solution directly.
