### ISSUE TITLE
Checkpoint match data to DB every 1000 rows

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#330]
As the match process takes longer and longer, we need to write the data out to the DB `pdp_contacts` table on a regular basis to allow restarts. Every 1000, 5000 rows?  

As the current end-of-run dump is < 1 second, there shouldn't be a performance hit.

**Comment by c-simpson** [comment]
From #313

**Comment by sposerina** [comment]
@c-simpson I suggest we close this. I like the idea that the entire matching process is done in one transaction. It either succeeds or fails and there is no partial states to clean up.

**Comment by c-simpson** [comment]
I'll buy that!
