### ISSUE TITLE
If classify says 0 new/0 updated, skip match? 

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#331]
If `rows_classified` says we have 0 new and 0 updated rows, is there any reason not to skip match_data and saving json?

https://github.com/CodeForPhilly/paws-data-pipeline/blob/4681add9e717eda88158ada075911c8399e41121/src/server/pipeline/flow_script.py#L36-L37

If no objections, I'll do a PR for this.

**Comment by sposerina** [comment]
@urirot  We can probably skip the matching but it's possible attributes not involved in the matching process updated so we could want to do the save as json process?

**Comment by c-simpson** [comment]
That makes sense. Do we use that json for anything?

**Comment by sposerina** [comment]
I'm not sure if the client uses the json at all or it's purely archival. 

Since the core of the matching logic is in the loop that iterates over the new and updated rules it effectively skips the matching when nothing has changed.
