### ISSUE TITLE
360 view: Dateutil parse error  

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#337]
Contact TT   - see #pdp-private

**Comment by c-simpson** [comment]
When r = (3259709, None, None, None, None, None, None, None, None, None, 'Kxxx Jxxxxxx') (it's about the 9th one, right after 3/7/2019)

https://github.com/CodeForPhilly/paws-data-pipeline/blob/654a74b78b8ec26fd16a4ae51c0d3f2799fca142/src/server/api/common_api.py#L94

throws a **TypeError: Parser must be a string or character stream, not NoneType**

(which seems a weird error - it's the data data that's None, not the parser)

**Comment by dcstlouis** [comment]
I ran into something like this yesterday and included a fix in PR #333. If you check out that branch, does that address what you were seeing?

**Comment by c-simpson** [comment]
I'll check it later today.
