### ISSUE TITLE
Should be consistent in date formats

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#339]
I'd choose ISO8601 but normal people may prefer MM-DD-YYYY.

![image](https://user-images.githubusercontent.com/11001850/120250447-2ccf0580-c24c-11eb-9dc0-9b7230aaf335.png)

**Comment by kfettich** [comment]
Go with yyyy-mm-dd

Putting the year in front will highlight if someone has been volunteering
for years, or just started this year
