### ISSUE TITLE
'mixed datatype' warning during Clean and Load 

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#343]
When running the matching analysis, this message appears:

`INFO in clean_and_load_data: Running load_paws_data on: salesforcedonations-2021-06-01--16-23-29.csv`   

`/app/./api/jwt_ops.py:24: DtypeWarning: Columns (16) have mixed types.Specify dtype option on import or set low_memory=False.`

It's my understanding that mixed types will slow pandas down (and from this message, probably increase memory usage).  

This may be a data quality issue at PAWS or maybe an export issue.

**Comment by kfettich** [comment]
is this the "Type" column in donations? it has values of "Recurring" and "One-time", but there are several rows at the top of the file that have blank values. I believe python has some issues with empty values - if I remember correctly it assumes the column is a numeric type when the first few values are empty, and then has to correct that assumption when it encounters string values later on. Can we define this column as a string up front, so it doesn't have to assume what it is? I think that may fix this.

**Comment by c-simpson** [comment]
@sposerina and I have been discussing exactly this by defining the DB structure in advance.
