### ISSUE TITLE
On server startup, check for incomplete execution

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#344]
As a step toward full async execution:   
When server starts up, check for remnants of an incomplete execution (i.e., non-completed job record in DB). Assuming we can know it's dead[1], delete the in-progress record to allow a new run to be started.

We might want to check execution_status last_update time to make sure there's nothing running in a another process

(From #313)

<hr>

[1] That's the hard part, isn't it?

**Comment by c-simpson** [comment]
#429 obviates this in cases of error, but we could still wind up in this situation if a pod was (for some reason) cycled in the middle of a run. 

We should consider how we can decide it's an old job and whether we want to display a "clean up old analysis" button.
This should probably tie into #336.

**Comment by kfettich** [comment]
no longer applicable since execution time has improved significantly
