### ISSUE TITLE
Update execution status every 100 rows

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#345]
We don't need to necessarily do the logging and DB update at the same rate.
The current 95,000 rows would result in 950 log entries, so maybe 200? is a better number.

  
   
From #313

**Comment by dkelley** [comment]
Sockets?

**Comment by c-simpson** [comment]
Decreasing execution_status intervals could make it easier to decide on #344   (How long since last completion?)
