### ISSUE TITLE
360 view: Foster Records section - missing recent fosters

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#354]

**Comment by jwtruver** [comment]
Need example data in order to investigate the issue. Karla to help us get this data. @kfettich

**Comment by kfettich** [comment]
see pdp-private for an example

**Comment by jwtruver** [comment]
We don't seem to be getting all of the information from the ShelterLove API. (@dcstlouis ) Donna, did additional research into the other items available from the ShelterLove API, and felt the API was not returning all of the data.

@kfettich will look into the adoption data to see if we are getting all the data we are anticipating for the adoption data.

Next Step-(@c-simpson ) will take a look at the foster data and see if we are getting all the data we are expecting. If we are getting all the adoption data, then we might remove the foster data and do more research. Reach out to ShelterLove, etc.

**Comment by jwtruver** [comment]
Cris looked into this. We do not have access into the Foster records. It was decided to remove the foster records from the UI for now.

Open an issue for importing foster records in "some way" ...the api is not able to export

**Comment by jwtruver** [comment]
closing
