### ISSUE TITLE
360 view: Show most recent volunteer activity

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#357]
Volunteer Activity Section - What is challenging here is that by looking at the info provided there is no way to actually know whether someone is an active volunteer or if they no longer volunteer. Maybe include the last volunteer date in this section so we can imply whether or not they are active.

**Comment by dkelley** [comment]
Do we need a backend task to return this data?

**Comment by c-simpson** [comment]
I think 
https://github.com/CodeForPhilly/paws-data-pipeline/blob/c91f728ff1ddd9cafcd5fd146fa8da5326876147/src/server/api/common_api.py#L88-L91

is doing it.  @dcstlouis  is that code doing what you need for this and #358 ?
