### ISSUE TITLE
360 view: Needs to show most recent shifts

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#358]
Volunteer History (Most Recent 3) - It is not showing the most recent shifts. While I understand that it is showing the breadth of types of volunteer work, it is still not selecting the date that reflects the most recent shift of that particular type of volunteer work.

**Comment by jwtruver** [comment]
front end piece of this should be done. this should be working. @sposerina  will ensure this is complete and close once confirmed.

**Comment by sposerina** [comment]
Confirmed shift data is up to date as of 5/31/2021
