### ISSUE TITLE
Add API endpoint for Support Overview

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#360]
#256 has a PAWS request for a Support Overview consisting of 
> First gift date
> First gift amount
> Lifetime giving
> Total # of gifts
> Largest gift
> Recurring Donor? [Y/N]
> PAWS Legacy Society? [Y/N]"

It would seem to make sense to return this data as a block.

**Comment by c-simpson** [comment]
@kfettich  I don't see any sign that we're getting **PAWS Legacy Society** in any of imports.  Where should we get that?

**Comment by c-simpson** [comment]
@kfettich  I don't see any sign that we're getting PAWS Legacy Society in any of imports. Where should we get that?

**Comment by kfettich** [comment]
Let's move the legacy society entry to v1.0 for now - it's not in our
current data sources and, from a quick look, I don't see a straightforward
way to get that from Salesforce. So adding this would be a bit more
involved. Let's ask Lauren about this during the feedback session.
