### ISSUE TITLE
Proposed table defintion for salesforcedonations

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#367]
Proposed definition for `salesforcedonations` table (blank cells in proposed are not implemented) 

|Current generated |Proposed|
|---|---|
|CREATE TABLE public.salesforcedonations (|  |
|	id text NULL,    |  id SERIAL,              |
|	"recurring_donor_-_a" bool NULL,   |   "recurring_donor" bool NOT NULL      |
|	opportunity_owner text NULL,  |                |
|	account_id_18 text NULL,  |                |
|	account_name text NULL,  |                |
|	primary_contact text NULL,  |        primary_contact text NOT NULL,          |
|	contact_id text NULL,  |         contact_id text NOT NULL,       |
|	opportunity_id_18 text NULL,  |                |
|	opportunity_name text NULL,  |                |
|	stage text NULL,  |                |
|	fiscal_period text NULL,  |                |
|	amount float8 NULL,  |      amount money NOT  NULL          |
|	probability float8 NULL,  |                |
|	age float8 NULL,  |                |
|	close_date text NULL,  |       close_date Date(time) NOT NULL         |
|	created_date text NULL,  |                |
|	"type" text NULL,  |        "type" text NULL [1],        |
|	primary_campaign_source text NULL,  |    primary_campaign_source text NULL,             |
|	"source" text NULL  |                |
|);

[1] This field should be either 'Recurring' or 'One-time' but is often blank.

Add: `CREATE INDEX salesforcedonations_contact_id_idx ON public.salesforcedonations USING btree (contact_id);`

**Comment by c-simpson** [comment]
Is there anything else we care about?

**Comment by c-simpson** [comment]
@sposerina  branch [367-sfd-table](https://github.com/CodeForPhilly/paws-data-pipeline/tree/367-sfd-table)  has new explicit definition (via Alembic) for `salesforcedonations` (below) which only has the columns we use.  Two concerns:

- I worry about about using reserved words ('type') for column names - change to 'donation_type'?
- We should look and see if it's safe to keep NOT NULL on   `type` and 	`primary_campaign_source` - are those always populated?

How do you want to handle the import into this? 

```
CREATE TABLE public.salesforcedonations (
	"_id" serial NOT NULL,
	recurring_donor bool NOT NULL,
	primary_contact varchar NOT NULL,
	contact_id varchar NOT NULL,
	amount numeric NOT NULL,
	close_date date NOT NULL,
	"type" varchar NOT NULL,
	primary_campaign_source varchar NOT NULL,
	CONSTRAINT salesforcedonations_pkey PRIMARY KEY (_id)
);
CREATE INDEX salesforcedonations_contact_id_idx ON public.salesforcedonations USING btree (contact_id);
```

**Comment by sposerina** [comment]
@c-simpson For now, we are still going to keep the files on the filesystem? I think we should avoid using reserved identifiers in the column names so I can update the schema to reflect your suggestions. My first instinct for the import is to iterate over the csv and use a batching mechanism that I'm hoping sqlalchemy provides. Another idea is to use a bulk import tool but since there is some massaging going on with the import files code is probably necessary so might as well do the whole process in code then.

**Comment by c-simpson** [comment]
I'd say to keep in the filesystem for now and then move to DB. I'll update the column to 'donation_type'.
