### ISSUE TITLE
Implement fuzzy matching for SFD column names

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#368]
Just about every version of the `salesforcedonations` file seems to have slightly different column names, such as **Contact ID (18 Digit)**  or **Contact ID 18**. As editing the files in Excel brings in its own set of problems, we need to be able to recognize the key columns. Issue #367 proposes dropping a number of these columns as [unused], so we need to figure out where to do that.

|In file |  Regex  |
|----|--|
|Recurring donor - A| |
|[Opportunity Owner]| |
|[Account ID 18]| |
|[Account Name]| |
|Primary Contact| |
|Contact ID 18| |
|[Opportunity ID 18]| |
|[Opportunity Name]| |
|[Stage]| |
|[Fiscal Period| |
|Amount| |
|[Probability (%]]| |
|[Age]| |
|Close Date| |
|[Created Date]| |
|Type| |
|Primary Campaign Source| |
|[Source]| |

**Comment by kfettich** [comment]
Just keep in mind we can't use fuzzywuzzy because of licensing incompatibility; whatever package we use needs to be MIT or MIT-compatible; let me know if you'd like me to look into licenses for anything in particular.

**Comment by c-simpson** [comment]
Jellyfish looks promising. 

@sposerina  How about this process for importing:

- strip out any non-alpha characters
- take a Jaro similarity of > .85 (?) as a match to the column name
- If each column header is a 'match', consider the file acceptable

At this point we could update the header cells with the correct column names and import via pandas, or load into DB explicitly. Given the columns to drop, the latter may make more sense.

**Comment by c-simpson** [comment]
Here's some sample Jaro similarity tests:

```
>>> j.jaro_similarity('Contact ID 18', 'Contact ID (18)')
0.9555555555555556
>>> j.jaro_similarity('Contact ID 18', 'Contact ID')
0.923076923076923
>>> j.jaro_similarity('Contact ID 18', 'Contact ID 18 Digit')
0.8947368421052632
>>> j.jaro_similarity('Contact ID 18', 'Contact ID (18 Digit)')
0.873015873015873
>>> j.jaro_similarity('Recurring Donor', 'Recurring Donor - A')
0.9298245614035089`
