### ISSUE TITLE
Remove LIKE in SFdonations query

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#370]
In get_360(), the query to get donations uses a LIKE with wildcard on the end. But since we have the full contact_id, is there any reason to wildcard? Can we just use '=' in the WHERE clause?

https://github.com/CodeForPhilly/paws-data-pipeline/blob/002c1f5aab97e9c43a26a76cafa33b9524cbf71d/src/server/api/common_api.py#L80-L84

**Comment by urirot** [comment]
don't see why not. let's change it. 
Let's address this one first: [360 issue](https://github.com/CodeForPhilly/paws-data-pipeline/issues/371)
