### ISSUE TITLE
360 ERROR - salesforcedonations and volgisticsshifts table are not found

### ISSUE THREAD

**Issue by urirot** [CodeForPhilly/paws-data-pipeline#371]
When calling the `'/api/360/<matching_id>'` endpoint, the function looks for matching contact_id from `salesforcedonations` and `volgisticsshifts` to fetch data for the tables. 

It seems like those tables aren't created anymore during the app initialization or after. 
this is the errors thrown when running locally:
```
   paws-compose-db | 2021-06-18 11:12:25.710 UTC [69] ERROR:  relation "volgisticsshifts" does not exist at character 15
   paws-compose-db | 2021-06-18 11:12:25.710 UTC [69] STATEMENT:  select * from volgisticsshifts where number = '3981576'
```
(same happens with `salesforcedonations`)
I wonder how come this is gone un-noticed, since this breaks 360 (I added try catch to even get the page loaded). maybe people are running the docker with an earlier version that does have those tables in the volume? 

I can investigate as well, but first waiting to see if @c-simpson  or @sposerina  have any idea, since I know you've made a lot of changes recently.

**Comment by c-simpson** [comment]
That's actually pretty old  (See https://github.com/CodeForPhilly/paws-data-pipeline/issues/181, from February). 
At one time, those tables were created explicitly in **models.py** , but at some point a change was made to have pandas create them. So if those files aren't uploaded, the tables don't get created, and you get those errors.  (I always uploaded from the short files to prevent that.)
@sposerina  and I have been discussing making table creation explicit again but haven't started on that.

The right thing to do here (and in general) is to catch the exception and return an empty result. I'm happy to do that.

**Comment by urirot** [comment]
This actually happened even when I uploaded all the files from the mini data

**Comment by dcstlouis** [comment]
Jumping in to say I was experiencing this issue when uploading and executing the mini-data files. Specifically, I got an error about the `volgisticsshifts` table. PR #373 should handle that, but not the `salesforcedonations` issue.

**Comment by urirot** [comment]
@dcstlouis Thanks for the quick fix. 
merged - closing.
