### ISSUE TITLE
Timout/refresh box now too small, 'under' the gray background

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#379]
Dialog box should be larger and definitely white again for contrast.   

(Changed with #377)
 
![image](https://user-images.githubusercontent.com/11001850/123015204-d611a300-d395-11eb-89b4-db158aa13aa6.png)

**Comment by urirot** [comment]
@c-simpson pushed a fix. think we can close this. 
Please take a look

**Comment by c-simpson** [comment]
Looks great.
