### ISSUE TITLE
Direct insert into volgisticsshifts

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#383]
With the apparent success of #382 for **salesforcedonations**,  we can do a similar thing for the **volgisticsshifts** table.

These appear to be the only fields we care about from the `Service` sheet:

- Number   (Let's change to `volg_id`, add index)
- Assignment
- From date
- Hours

**Comment by c-simpson** [comment]
@dcstlouis ,  @kfettich Anything we're missing here?

**Comment by kfettich** [comment]
I'd suggest including "Site" as well; the info is already included in
"Assignment" but if we include this column, we won't have to parse
"Assignment" when the time comes to show *where* a volunteer is active.

**Comment by c-simpson** [comment]
@sposerina  I'm currently catching the upload
https://github.com/CodeForPhilly/paws-data-pipeline/blob/c99700162636cd190a556a9f1f9be1fe782b5920/src/server/api/file_uploader.py#L39-L45
 and if name includes 'volunteer', redirecting it.    But since we need to do matching on the volunteer file, should I also let it flow through to `excel_to_dataframes()` ?
