### ISSUE TITLE
Use reduced set of records by default

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#385]
Importing and matching are slow, but it's not usually necessary to process a full data set to find problems. 

Proposal:
Select a list of IDs (100 to start) from each data source that gives us a good mix of records for testing importing and matching (e.g., people in three sets, people in SF and SL, people in Vol and SF, donations/no donations). Then in the import code for each source, we can do something like  `  if  contact_id in short_list['salesforcedonations']: `  unless the `USE_FULL_DATA` environment variable is set.

By having known records we can also start developing tests dependent on them.

**Comment by c-simpson** [comment]
@urirot  @sposerina

**Comment by jwtruver** [comment]
we are going to use fake data in the .xlsx files as needed for testing
