### ISSUE TITLE
RFM - Data Display and sort Options

### ISSUE THREAD

**Issue by jwtruver** [CodeForPhilly/paws-data-pipeline#388]
@kfettich and Ben
Research potential "display and sort" options for the RFM output
Both from a use and UI perspective
To share results with team over slack by 210716

**Comment by kfettich** [comment]
See: https://codeforphilly.slack.com/archives/C013HTDAJ4V/p1627351522087300 for display and sort UI concept; only display salesforce row per contact (no need for all data sources to show up in the list, as RFM is calculated exclusively for donors, and other info will show up in 360); each row should be clickable and should take the user to the 360 report for that donor

**Comment by jwtruver** [comment]
color code based on category. left hand selection "similar to yelp"; if selecting "champions" more than one category on the left, the read out on the right contains the selections. sort on the right should be "sorted alphabetically by last name", clicking on the line should take Lauren to the 360 view. (no sort selction...just sorts alphabetically automatically.

**Comment by jwtruver** [comment]
Uri will double check it's current default sort order.

**Comment by jwtruver** [comment]
#392

**Comment by jwtruver** [comment]
combined into #410 with (Combine #388 and #392)
Combine #388 and #392 - Add RFM to Contact Table (RFM Scores in the lines, search options we wanted, etc.)
