### ISSUE TITLE
RFM - Calculate RFM and Upload Data into PDP Contacts Table

### ISSUE THREAD

**Issue by jwtruver** [CodeForPhilly/paws-data-pipeline#390]
@c-simpson @urirot @sposerina @dkelley 

Goal to complete by 210727 to ensure UI work for display and sort can begin
Output from Karla and Ben to be used to:
Implement business rule definitions for RFM
Program business rules
Calculate individual RFM values
Upload to the PDP Contacts table as R/F/M individual columns and one RFM column? (to be decided by team)

**Comment by c-simpson** [comment]
@bdeck8317  and I discussed this and the best storage implementation seems to be an `rfm` text column in `pdp_contacts`  which holds the score for each **matching_id** and a separate table relating rfm values to labels to which we can join as needed:


rfm_value | label
--|--
'111' | 'Prospect'
 ..  |  ..
'555' | 'Star' 


I've suggested that the best format for updating the DB would be a list of (matching_id, 'rfm_score') tuples:
`[ (1,'123'), (2,'543'), (3,'555')]` 

<hr>
@sposerina  Until we get pandas out of the SQL business should I just create a separate rfm table  that pandas won't touch?

matching_id  | rfm_value
--|--
1 | '443'
 ..  |  ..
'65667' | '225'

**Comment by c-simpson** [comment]
We should probably add the color value to the mapping column.

rfm_value | label | color
--|--|--
'111' | 'Prospect'|'0xe0e0e0'
 ..  |  ..
'555' | 'Star'|'0x00f000'

**Comment by jwtruver** [comment]
Potentially an aggregation could be done in a "view". We can use the color-coding from the website Karla showed. Color is based on the label and value. The logic identifies the score, then the score is assigned a label and then the color is assigned. Ben will ensure the bin parameters are passed into the functions and not hardcoded. Bin parameters will be stored in the database. (a third table for the bin definitions)

**Comment by c-simpson** [comment]
@bdeck8317 
RFM 'edge value' table:
rfm_value |  data
--|--
'R' | '{0:0, 1:45, 2:89, 3:213, 4:770}'
 ..  |  ..
'M' | '{0:0, 1:4000, 2:7345, 3:14567, 4:67890}'

**Comment by bdeck8317** [comment]
@c-simpson Have you already created the table? If so, would you prefer I just give you the values to update the table or should I give you a `.txt` doc in a specific format?

**Comment by jwtruver** [comment]
will close upon merge
