### ISSUE TITLE
Improve Foster Records Import

### ISSUE THREAD

**Issue by jwtruver** [CodeForPhilly/paws-data-pipeline#393]
A continuation of closed issue #354 (https://github.com/CodeForPhilly/paws-data-pipeline/issues/354)

We do not have access into the Foster records. It was decided to remove the foster records from the UI for now.

Open an issue for importing foster records in "some way" ...the api is not able to export

**Comment by c-simpson** [comment]
The SL API does not provide foster info in particular, but does provide an **Animal Events** endpoint.  To gather foster events, we'd need to

- Use the **Animals** feed to collect the IDs of all animals who have come though PAWS
- Then use the **Animal Events** endpoint to get the Events associated with each animal
- Filter the Events data to keep just the foster events
- Populate a db table something like this  



person_id | animal_id | date | event
--- | --- | --- | ---
12345|987654321|2020-09-17|Foster.Out
12345|987654321|2020-10-16|Foster.Return

Then we could get the foster events for the 360 view by going from match_id -> shelterluv.person_id and returning all the events associated with the person.

This might be something @uri could add into his SL people scheduled data pull.

**Comment by urirot** [comment]
@c-simpson Looks like we are already gathering this data on each 360 request. don't think we have any records like foster or adoption in our permanent data set.

take a look here in the common_api endpoint. by what you're describing it looks like the foster data should already be available to us. @dcstlouis I know have already been looking into that. I wonder what was missing. 
can one of you clarify?

**Comment by c-simpson** [comment]
@urirot My guess is that somebody expected it would be available in the SL  API **Person Details** endpoint, but it only provides a list of *adopted* animals.
