### ISSUE TITLE
Import data into RFM tables

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#399]
A continuation of #390   (the import part)

**Comment by bdeck8317** [comment]
@c-simpson  

Customer labels
`
'{"Champions": {"R_score": [4, 5], "FM_score": [4, 5]}, "Loyal Customers": {"R_score": [2, 5], "FM_score": [3, 5]}, "Potential Loyalist": {"R_score": [3, 5], "FM_score": [1, 3]}, "Recent Customers": {"R_score": [4, 5], "FM_score": [0, 1]}, "Promising": {"R_score": [3, 4], "FM_score": [0, 1]}, "Customers Needing Attention": {"R_score": [2, 3], "FM_score": [2, 3]}, "About to Sleep": {"R_score": [2, 3], "FM_score": [0, 2]}, "At Risk": {"R_score": [0, 2], "FM_score": [0, 2]}, "Can\'t Lose Them": {"R_score": [0, 1], "FM_score": [4, 5]}, "Hibernating": {"R_score": [1, 2], "FM_score": [1, 2]}, "Lost": {"R_score": [0, 2], "FM_score": [0, 2]}}'
`

**Comment by jwtruver** [comment]
Cris has prepared a .csv importer; builds a list and feeds it into the insert function. need to consider where to put into the api infrastructure and can be merged.
