### ISSUE TITLE
Generate raw data for running RFM scoring

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#405]
Scoring code needs 
`matching_id, donation amount, close_date`

Like #404, all contact_ids associated with the matching _id need to be combined.

**Comment by bdeck8317** [comment]
@c-simpson  

Hey we also need to include one other piece of info from each row, `account_name`.

We need this so we can determine if they are a private citizen or if they are a corporation/business.

**Comment by c-simpson** [comment]
@bdeck8317  As this has already been merged, please re-close this issue and create a new one. Assign it to me and tell me the source for the `account_name`  field.  Thanks.
