### ISSUE TITLE
Add RFM to Contact Table (RFM Scores in the lines, search options we wanted, etc.)

### ISSUE THREAD

**Issue by jwtruver** [CodeForPhilly/paws-data-pipeline#410]
Combine #388 and #392 - @urirot @kfettich @c-simpson 

@kfettich and Ben
Research potential "display and sort" options for the RFM output
Both from a use and UI perspective
To share results with team over slack by 210716

See: https://codeforphilly.slack.com/archives/C013HTDAJ4V/p1627351522087300 for display and sort UI concept; only display salesforce row per contact (no need for all data sources to show up in the list, as RFM is calculated exclusively for donors, and other info will show up in 360); each row should be clickable and should take the user to the 360 report for that donor

color code based on category. left hand selection "similar to yelp"; if selecting "champions" more than one category on the left, the read out on the right contains the selections. sort on the right should be "sorted alphabetically by last name", clicking on the line should take Lauren to the 360 view. (no sort selction...just sorts alphabetically automatically.

Complete and test for rollout by mid August
Report "like" "sort capabilties"
Display results by RFM score in some way (follow up with Lauren)
Very open definition while actual need is determined

**Comment by c-simpson** [comment]
See PRs #412 and #415 which provides the backend support for rfm (dummy)  scores, labels, and colors.

**Comment by jwtruver** [comment]
We have a separate table it will join to...Scores table, and mapping table. we are closing this item.
