### ISSUE TITLE
Create mock functions for 360 Shelterluv requests

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#425]
If the SL TOKEN is not available, return fake but valid responses to: 

- /api/person/<matching_id>/animals
- /api/animal/<animal_id>/events
- /api/person/<matching_id>/animal/<animal_id>/events

The animals can be 'Fake Cat' and 'Fake Dog', and we can link to the default animal images.

**Comment by c-simpson** [comment]
@urirot @dcstlouis   It appears that we don't use the `/api/animal/<animal_id>/events` endpoint any more, just the `/api/person/<matching_id>/animal/<animal_id>/events` one.

Can you confirm this? If true, should we remove it?

**Comment by dcstlouis** [comment]
@c-simpson Can confirm. I'd say we should remove it.

**Comment by c-simpson** [comment]
This seems to be a dup of #458

**Comment by mrcrnkovich** [comment]
I thought this was closed in January with #477

**Comment by kfettich** [comment]
Out of scope
