### ISSUE TITLE
Clicking on contact triggers 'volunteer.life_hours is undefined' React error

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#433]
See #pdp_private for name.    /api/360 returns five shifts (18, 18, 4, 8, 4   hours) but below error is thrown.

![image](https://user-images.githubusercontent.com/11001850/134439105-4f6cf6c4-fddc-4abd-bb4a-f0413488edbf.png)

this.props.volunteer.start_date is "Invalid date", which doesn't seem to be handled by VolunteerActivity.js: 

```
                                        (this.props.volunteer.start_date === "N/A")
                                        ? "N/A" 
                                        : moment(this.props.volunteer.start_date).format("YYYY-MM-DD")
```

**Comment by c-simpson** [comment]
First date for this volunteer is '2013-02-10' . 
Is code in View360.js/extractVolunteerActivity() expecting MM-DD-YYYY ? 
```
                volunteerActivity["start_date"] = moment(volunteerActivity["start_date"], "MM-DD-YYYY").format("YYYY-MM-DD");
```

**Comment by dcstlouis** [comment]
Yes, I believe so. The lifetime hours value wasn't in the database before, and the workaround was retrieving it from the `json` column in `pdp_contacts`. I'll update it so it pulls from `volgisticsshifts` instead. Thanks!
