### ISSUE TITLE
Create status page for PAWS users

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#437]
We're starting to see things we need to display to the user

- Status of recent data uploads and analyses
- Problems with e.g., RFM scoring 
- Errors that require review

We could try to flag each contact that there was a scoring problem or just create a status page and set a <!> flag on the top bar until the user reviews the notes.  (Maybe only Admins can clear? Or see at all?)

We need to figure out how not to re-show messages already seen. It seems the easiest thing to do would be to stores messages in a DB table and we can flag when seen (but they'll still be around for us to review).

**Comment by kfettich** [comment]
Stale issue. Any errors will be logged via the back-end.
