### ISSUE TITLE
Create Volgistics matches data report

### ISSUE THREAD

**Issue by urirot** [CodeForPhilly/paws-data-pipeline#44]
Create a CSV that shows all conflicts and errors.

- add to flow script

**Comment by urirot** [comment]
Create a CSV that shows all conflicts and errors.
Example:

| hyperlink salesforce entity | salesforce duplicate  |  Volgistics conflict  | Volgistics duplicate  |   |
|---|---|---|---|---|
|  |   |   |   |   |
|   |   |   |   |   |
|   |   |   |   |   |


example for hyperlink:
https://brave-fox-riktj8-dev-ed.lightning.force.com/lightning/r/Contact/0036g000008tN9wAAE/view
the random string should be Contact.ID field

**Comment by bbucior** [comment]
Still need to:

- [ ] Validate the current workflow with sample data (are the matches/mismatches reasonable?)
- [ ] Run the Docker workflow locally on real data
- [ ] Update the matching rules per documentation, such as matching_rules.md
