### ISSUE TITLE
Frequency Calculation Issue

### ISSUE THREAD

**Issue by jwtruver** [CodeForPhilly/paws-data-pipeline#457]
Issue has been identified with the calculation of Frequency, perhaps doing something with the overall timeframe delineating the calculation. To ensure proper context, research should also be done to ensure R and M are being calculated with the same timeframe delineations.

**Comment by c-simpson** [comment]
Branch [457-fixes](https://github.com/CodeForPhilly/paws-data-pipeline/tree/457-fixes) seems to fix the frequency calculation. Karla will recalculate the bin edges.

**Comment by jwtruver** [comment]
Some adjustments have been made to the code. Recalculated Bins have been made as well. Looking back 12 months for frequency and recency and lifetime for monetary value. Anything more recency for last 12 months is 2 or higher. (more than 1 year ago...score of 1) Last quarter, score 5, second quarter 4, ....3rd score of 3 etc.

last upload is the reference date...(recency and frequency only)
Monetary value...is lifetime donations...

Frequency (this was the main issue that was researched and corrected)--care about the last 12 months. (Behavior of donors over the course of a year) once in the past 12 months...score of 1. twice per year...score of 2...donate once a quarter score of 3...once a month score of 4...donate more than once a month is a score of 5...(if you did 18 donations over the past 12 months then you get a 5)..date of the last upload is the reference date...

Monetary value bin delineations...Karla will upload all new calculations for proper testing...
0-50
50-75
75-100
100-210
210 or more!

Testing from Karla and Cris - Things have looked great!
