### ISSUE TITLE
Verify proper handling of 'Facebook Bucket' donations

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#473]
The `Salesforce_PAWS Donation_11_16_2021_TO_12_02_2021.xlsx` file has a number of donations where **Account Name** is 'Facebook Bucket' with no **Primary Contact** and  no **Contact ID**. 

It looks like `donations_importer.py/validate_import_sfd()` should skip these for lack of **Contact ID**. Is this the right behavior?

**Comment by kfettich** [comment]
We need to do more research into the Facebook Bucket category; I
noticed these donations too - they are coming from FB, and as per Lauren,
this data is not automatically matched to people, so any matching is done
manually where possible. Let's skip these in the pipeline for now, as we
may need to work on a separate flow to import data from FB directly (and
hopefully more efficiently)

**Comment by kfettich** [comment]
Out of scope
