### ISSUE TITLE
Handle bad animal_id in  get_person_animal_events()

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#479]
In common_api.py, `get_person_animal_events()` will throw a KeyError  (and return a 500) if an invalid `animal_id` is passed in.

SL returns "{'error_message': 'Invalid animal id 12222345'}"

This code checks for error message:

```        
            event_details = requests.get(animal_url, headers={"x-api-key": SHELTERLUV_SECRET_TOKEN}).json()

            if 'error_message' in event_details :
                current_app.logger.warn("Bad animal_id (" +  str(animal_id) +  ") passed to get_person_animal_events()")
                return '{}'

            for event in event_details["events"]:
                for record in event["AssociatedRecords"]:
                    if record["Type"] == "Person" and record["Id"] == shelterluv_id:
                        events.append(event)
            result[animal_id] = events
```

Is there a better way to handle?

This was uncovered by @mrcrnkovich's test for SL mocking.
@sposerina   Let's restart the discussion about dummy records for testing.

**Comment by kfettich** [comment]
Given scope change for MVP, it's unlikely we'll be sending invalid animal IDs.
