### ISSUE TITLE
Create orientation documentation (look at other CfP projects - Chime & MatchMapper)

### ISSUE THREAD

**Issue by jwtruver** [CodeForPhilly/paws-data-pipeline#498]

**Comment by jwtruver** [comment]
https://github.com/CodeForPhilly/chime

https://github.com/CodeForPhilly/MATchMapper

**Comment by kfettich** [comment]
[User Documentation](https://paws-data-pipeline.gitbook.io/user/)
[Developer Documentation](https://paws-data-pipeline.gitbook.io/developer/)
