### ISSUE TITLE
An admin user can upload a Volunteer dataset

### ISSUE THREAD

**Issue by jwtruver** [CodeForPhilly/paws-data-pipeline#503]

**Comment by kfettich** [comment]
Instructions:

- Log in to Volgistics, go to Print -> Table Style Reports -> Excel Spreadsheet -> "All volunteer information (stock)"
- When the report is done, an email will appear in the Volgistics Mailbox with the subject "All volunteer information (stock)"; clicking on this message will save the excel file to your computer
- Go to the pipeline website, log in as admin, go to "Admin" tab, select the volgistics file from your Downloads, and click Upload
- Upload can take a few minutes; when the upload is done, there may not be immediate feedback; navigate to a different tab and then back to the Admin tab to see if the "Last Updated" date was refreshed
- Done! The data will be used the next time the pipeline runs
