### ISSUE TITLE
If there is a data breach, PAWS will be notified as asap

### ISSUE THREAD

**Issue by jwtruver** [CodeForPhilly/paws-data-pipeline#509]

**Comment by kfettich** [comment]
Is there a way to tell if there is/was a data breach? Can we automate some notifications?

**Comment by c-simpson** [comment]
An attempt at fleshing this out: [Q&A on breaches](https://github.com/CodeForPhilly/paws-data-pipeline/wiki/Q-&-A-on-breaches)

**Comment by c-simpson** [comment]
Jan 10 consensus: truncate data soon* after updating SF.

*'Soon' TBD
