### ISSUE TITLE
"Execute Current Sources" returns error [locally]

### ISSUE THREAD

**Issue by kfettich** [CodeForPhilly/paws-data-pipeline#55]
Steps to replicate error:

1. Pull latest code from GitHub master
2. In Docker Quickstart Terminal (Windows), run:
```
docker image build -t paws-data-pipeline . 
docker container rm pdp
docker container run --publish 5000:5555 --name pdp -d paws-data-pipeline
```
3. Go to http://10.147.20.146:5000/ (production app) and download 

- salesforcecontacts-2020-04-14--23-08-57.csv
- volgistics-2020-04-14--22-51-07.csv

4. Go to local app, upload those 2 files
5. Click "Execute Current Sources" 

--> Error![Errno 2] No such file or directory: '/app/static/output/logs/excluded_salesforcecontacts.csv'

When looking at the db inside the docker container, it only contains the table 'salesforcecontacts', nothing else. Also no other outputs are generated, beyond this db.

**Comment by sposerina** [comment]
I believe this is resolved. Just needs to be verified and closed.
