### ISSUE TITLE
Update contributors

### ISSUE THREAD

**Issue by osabahat** [CodeForPhilly/paws-data-pipeline#557]
Update About page with any remaining team members and the span of the project:

https://github.com/CodeForPhilly/paws-data-pipeline/blob/master/src/client/src/pages/About.js

**Comment by kfettich** [comment]
Developers: 
- Osman Sabahat
- Stephen Carroll
- Diego Delgado
- Carlos Dominguez
- Benjamin Deck

-- more to be added
