### ISSUE TITLE
create some data integrity rules for matching criteria

### ISSUE THREAD

**Issue by sposerina** [CodeForPhilly/paws-data-pipeline#588]
Two emails of a zero length should not count as valid matching criteria. Some other placeholder text noted was "unknown" for name and one digit phone numbers "+1". Fields with these values should never be considered a positive match.

**Comment by kfettich** [comment]
do not consider to be a match if: 

- first name and last name contain the string "unknown"
- first name and last name are equal to "8"
- first name and last name are equal to "?"
- first name = "John" and last name = "Doe"
- first name = "No Name" and last name = "No Name"
- first name = "No" and last name = "Name"
- first name = Null and last name = "Friends"
