### ISSUE TITLE
Uploader should not expect a consistent data structure, but should expect that core variables are present and named consistently

### ISSUE THREAD

**Issue by kfettich** [CodeForPhilly/paws-data-pipeline#59]
Variables can change positions in uploaded data, but as long as the required variables are there, the uploader should not return an error

**Comment by urirot** [comment]
@kfettich we currently determine that by the name of one of the columns: so just if x exists we decide it's of type y:
   'Account Name' column exists  ->         'salesforcecontacts',
    'Last.name..First.name' ->  'volgistics',
    'Animal.ID' ->             'petpoint',
    'Recurring.donor' - >     'salesforcedonations'

if this is enough you can close this one.
