### ISSUE TITLE
Deploy database

### ISSUE THREAD

**Issue by dtromero** [CodeForPhilly/paws-data-pipeline#6]
The DB must be persistent and not tied to the docker container that has the data processing scripts

**Comment by mike-bailey** [comment]
Discussion was had regarding what database to move to. Right now, we are using SQLite 3. I noted at a minimum where that container is needs a host mount point. @urirot indicated he may want it in another container or determining whatever Linode has that's hosted (like RDS).

**Comment by themightychris** [comment]
CfP ops wants containers to deploy at this point, Linode does not have a managed database offering and we're not using their higher-level products directly. Using a postgres container would put you in line with most others projects

**Comment by mike-bailey** [comment]
Well that certainly answers that. Thank you.

**Comment by urirot** [comment]
@sposerina 
we can add the postgress DB container with the docker compose, from the branch @mike-bailey adde.
https://github.com/CodeForPhilly/paws-data-pipeline/compare/postgresql_and_compose

**Comment by mike-bailey** [comment]
Even though I've been MIA from meetings, please feel free to contact me with Qs if any. I'm not totally off the face of the earth 😄

**Comment by ckohl226** [comment]
I asked Chris A about persistence, like for the database to survive through restarts of a docker container.  I got the following answer back.  May be useful as we move ahead:   Docker containers can have persistent places in their filesystem. Simply designate a named volume in docker-compose and when we deploy to production we'll attach a persistent volume to that same path. This can be done either with a raw file directory or database data

**Comment by mike-bailey** [comment]
+1 that's the proper way. I proposed this early on in meetings, but because I think people thought we were using a managed DB service it got buried.

**Comment by mike-bailey** [comment]
Here's where I did it in my compose file https://github.com/CodeForPhilly/paws-data-pipeline/commit/db829137fa7273551006322163dce1bb1143668e?diff=unified#diff-4e5e90c6228fd48698d074241c2ba760R7
