### ISSUE TITLE
Create table output from datasources with all attributes for matching records (e.g. user adopted, donated and volunteered)

### ISSUE THREAD

**Issue by dtromero** [CodeForPhilly/paws-data-pipeline#8]
Determine columns that would be most helpful for the persona. Create a sample report based on those columns.

**Comment by nimandesign** [comment]
Spreadsheet/user-friendly way of people involved with PAWS
Sortable / filterable by Volunteer, Adopter, Donator
PAWS Contact Name
Address
Other PII
Donations
- Made donation (Y/N?)
- Last made
- Total
Volunteer
- Has volunteered (Y/N?)
- Last time volunteered
- Total volunteer hours
Adoptions
- Number of adoptions
- Per adoption:
    - Date
    - Pet type
    - Name

Mismatches, missing information, and other issues are identified
