### ISSUE TITLE
Define components of 360-degree report

### ISSUE THREAD

**Issue by kfettich** [CodeForPhilly/paws-data-pipeline#80]
# 360 degree report

## Contact Info
**Name**: Jane Doe
**Current Address**: 123 ILivehereNow St. Philadelphia PA (last update: 5/15/2020 + Source)
**Current Phone Number(s)**: 123-456-7890 (last update: 5/10/2020)
**Email address(es)**: myemailaddress@somedomain.com (last update… )
**Summary**: This person engages with PAWS since 01/02/2005; they have been involved as a volunteer since 2010 (link), adopter since 2012 (link) and donor since 2017 (link). Adoption records: 1 dog, 0 cats; foster records: 3 dogs, 8 cats.

## Donations
_PAWS staff will upload the "Salesforce - Donation Data" data from Salesforce; the system will need to look up the Individual's `Contact ID` in "Salesforce - Accounts and Contacts", extract `Account ID`, then look up this ID in `Account ID` in "Salesforce - Donation Data" to extract donations info for this person._ 

**List of most recent donations (top 5 + “more” button)**:  
**Date of Donation**: [Salesforce Donations variable: `Close Date`]
**Amount**: [Salesforce Donations variable: `Amount`]
**Campaign Type**: [Salesforce Donations variable: `Primary Campaign Source`]

| Date of Donation | Amount | Campaign Type |
| --------- | --------- | --------- | 
| 2020-01-15 | 35 | PAWS: Monthly Giving |
| 2019-12-15 | 35 | PAWS: Monthly Giving |
| 2020-11-15 | 35 | PAWS: Monthly Giving |
| 2019-06-01 | 150 | Chefs' Night For PAWS Sponsorship Opportunities |

## Adoption records (Hyperlink to PetPoint)
_PAWS staff will be asked to export the "AnimalIntakeWithResultsExtended" report from PetPoint and upload it into the interface_ 

**Animal name**: [Petpoint variable: `Animal Name`]
**Type or Species**: [Petpoint variable: `Animal Type`]
**Primary breed**: [Petpoint variable: `Primary Breed`]
**A-number**: [Petpoint variable: `Animal #`]
**Date of adoption**: [Petpoint variable: `Release Date`]
**Current age**: [Current Date - Petpoint variable: `Date Of Birth`]

| Animal Name | A-Number | Species | Breed | Age | Adoption Date | 
| --------- | --------- | --------- | --------- | --------- | --------- | 
| Buffy | A123456 | Cat | | 13 | 2/1/2018 |

## Foster records (Hyperlink to Petpoint)

| Animal Name | A-Number | Species | Breed | Age | Foster Date | 
| --------- | --------- | --------- | --------- | --------- | --------- | 
| Peter Barker | A778245 | Dog | | 8 | 6/1/2020 |
| Momo | A906291 | Dog | | 4 | 11/4/2019 |

## Volunteer Activity
_PAWS staff will have to upload the file "All volunteer information (stock)" from Volgistics; the following data comes from Sheets within the excel file: Master, Assignments, Service, Regular_schedule; NOTE: hyperlinks not possible because Volgistics doesn't allow them_

**Volunteer activity start**:  6/1/2016 [Vogistics/Master variable: `Start date`]
**Life hours**: 200 [Volgistics/Master variable: `Life hours`]
**YTD hours**: 30 [Volgistics/Master variable: `YTD hours`]

FIELDS FOR INCLUSION POST MVP
**Assignment Site(s)**: [Volgistics/Assignments variable: `Site`]
**Assignment(s)**: [Volgistics/Assignments variable: `Assignment`]
**Latest shift**: [Volgistics/Service variable: `From date`]
**Regular schedule**: [Volgistics/Service variable: `Site`, `Assignment`]
[MAYBE: Animal record has changed since date of adoption: Yes/No]

**Comment by jkdru** [comment]
Suggestion: Would it be helpful for Summary to identify also # of animals? Example: "... Their adoption records include 1 dog, 0 cats and their foster records 3 dogs, 8 cats."
