### ISSUE TITLE
UI - 360 degree view page

### ISSUE THREAD

**Issue by urirot** [CodeForPhilly/paws-data-pipeline#82]
- have a search by name that sends a substring /contacts/<search_text>
- hitting search will return all relevant name matches from all data sources (currently returns it from salesforcecontacts)
- show a dropdown of the matches that returns as [name(email)] so if a name appears twice we can differentiate. 
- when a name is picked send a new request to get all the data from master 360/<name>
- show the following to the user for each source that exists in the response:
[360 issue](https://github.com/CodeForPhilly/paws-data-pipeline/issues/80)

**Comment by mrcrnkovich** [comment]
Hoping to finalize this tonight before the call tomorrow.
