### ISSUE TITLE
UI - Dropdown fixes and improvements

### ISSUE THREAD

**Issue by urirot** [CodeForPhilly/paws-data-pipeline#94]
We started to use real data, and some new problems appeared that we haven't thought of yet.

* Handling many results - limit results of the dropdown to 200. 
     * Have a message when results are greater then 200, saying (showing 100 results out of X - try adding more letters to your search)
* Make the user understand when there are results in the dropdown. after hitting the search button, something should happen. 
* validate that at least 3 characters are entered before the search button is enabled. have some message that says "must enter 3 at least characters" or something similar.

**Comment by mrcrnkovich** [comment]
Fixed issues #2 and #3. I'll work on limiting the results w/ a dialog tonight.
